import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  cabecalho: {
    height: '15%',
    backgroundColor: '#082777',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: 20,
  },
  textoCabecalho: {
    fontSize: 25,
    fontFamily: 'Inter_400Regular',
    color: '#FFFFFF',
  },
  conteudo: {
    flex: 6,
    // height: '85%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 50,
  },
  textoTitulo: {
    fontSize: 38,
    fontFamily: 'Inter_500Medium',
    color: '#082777',
    marginBottom: 28,
  },
  toggleLogin: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    marginBottom: 35,
  },
  toggleTextOn: {
    color: '#4B93E7',
    textAlign: 'center',
    fontFamily: 'Inter_500Medium',
    fontSize: 28,
    borderBottomWidth: 3,
    borderBottomColor: '#F7AC25',
  },
  toggleTextOff: {
    color: '#91BDF5',
    textAlign: 'center',
    fontFamily: 'Inter_300Light',
    fontSize: 18,
  },
  verticalLine: {
    width: 2,
    height: 28,
    borderRadius: 1,
    backgroundColor: '#828282',
  },
  horizontalLine: {
    width: 40,
    height: 1,
    borderRadius: 1,
    backgroundColor: '#828282',
  },
  campoEntrada: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 13,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DDEAFB',
    borderRadius: 8,
    height: 40,
    width: 245,
    paddingHorizontal: 10,
    color: '#082777',
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
  },
  inputEmail: {
    flex: 1,
    color: '#082777',
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
  },
  checkboxForgetPassContainer: {
    width: 245,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    alignSelf: 'center',
    marginRight: 3,
  },
  label: {
    marginLeft: 2,
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#082777',
  },
  anotherOption: {
    flexDirection: 'row',
    gap: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 15,
  },
  buttonEntrar: {
    width: 245,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#F7AC25',
    shadowColor: 'rgba(0, 0, 0)',
    shadowOffset: '0px 4px 8px 0px',
    shadowOpacity: 0.16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  buttonGoogle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 245,
    height: 30,
    borderRadius: 8,
    gap: 8,

    backgroundColor: '#4B93E7',
    shadowColor: 'rgba(0, 0, 0)',
    shadowOffset: '0px 4px 8px 0px',
    shadowOpacity: 0.16,
  },
  textButton: {
    color: '#FFFFFF',
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
  },
});
